-- AlterTable
ALTER TABLE "Wallet" ADD COLUMN     "expenses" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "incomes" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "initial_balance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ALTER COLUMN "balance" SET DEFAULT 0;
